name: Java CI with Maven and Docker

on:
  push:
    branches: [ "master" ]
jobs:
  build:

    runs-on: docker

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install Maven
      run: |
        sudo apt update
        sudo apt install -y maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml spring-boot:build-image -DskipTests

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push Docker image
      run: docker push docker.io/yobange/spring-server:latest
      
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker stop spring-container
          docker rm spring-container
          docker rmi yobange/spring-server:latest
          docker pull docker.io/yobange/spring-server:latest
          docker run -d --network postgres-spring -p 8080:8080 --name spring-container \
          -e DB_IP=${{ secrets.DB_IP }} \
          -e DB_PORT=${{ secrets.DB_PORT }} \
          -e DB_USER=${{ secrets.DB_USER }} \
          -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -e SERVER_PORT=${{ secrets.SERVER_PORT }} \
          docker.io/yobange/spring-server:latest
